# Configuration file for kapp pipeline

# Homomeric kmax calculation for E. coli (iML1515) using 
# the Davidi et al. 2017 growth conditions (uptake rates 
# and growth rate), with condition-specific proteomics

# ========= MODEL CONFIGURATION =========
organism: "ecoli"
model_path: "data/raw/gems/iml1515.xml"
solver: "cplex"
flux_method: "pFBA"
run_fva: false
include_growth: true
calculate_eta: true
save_kapp: true
specific_proteome: true


# ============ OUTPUT FOLDER ============
folder_id: "davidi_specific"


# ============== PARAMETERS =============
upper_threshold: 1.0e6   # Upper limit for kcat_app (s⁻¹)
lower_threshold: 1.0e-5  # Lower limit for kcat_app (s⁻¹)


# ================ FILES ================
medium_df: "data/processed/medium/davidi_medium.csv"
proteomics_path: "data/raw/davidi_kcat/davidi_abundance.csv"
substrate_df: "data/processed/substrates/iml1515_substrates.csv"
sequence_df: "data/processed/uniprot/ecoli_uniprot_seqs.csv"
