# Configuration file for kapp pipeline
# Homomeric kmax calculation for E. coli (iML1515) using a random medium

# ==== Model Configuration ====
organism: "ecoli"
model_path: "data/raw/gems/iml1515.xml"
solver: "cplex"
flux_method: "pFBA"
calculate_eta: false

# ==== Flux Simulation Parameters ====
medium_df: "data/processed/amns/conditions_test.csv"

# ==== Proteomics Parameters ====
p_total: 0.55
paxdb_path: "data/raw/paxdb/ecoli_whole_organism_integrated_511145.txt"

# ==== Input Data Files  ====
substrate_df: "data/processed/substrates/iml1515_substrates.csv"
sequence_df: "data/processed/uniprot/ecoli_uniprot_seqs.csv"

# ==== Folder ID for output directory====
folder_id: "ecoli_test"

# ==== Filtering Thresholds ====
upper_threshold: 1.0e6   # Upper limit for kcat_app (s⁻¹)
lower_threshold: 1.0e-5  # Lower limit for kcat_app (s⁻¹)
