# Configuration file for kapp pipeline

# Homomeric kmax calculation for E. coli (iML1515) using 
# the AMN predicted uptake rates from Faure et al. 2023

# ========= MODEL CONFIGURATION =========
organism: "ecoli"
model_path: "data/raw/gems/iml1515.xml"
solver: "cplex"
flux_method: "pFBA"
run_fva: false
include_growth: false
calculate_eta: true
save_kapp: true
specific_proteome: false


# ============ OUTPUT FOLDER ============
folder_id: "faure"


# ============== PARAMETERS =============
p_total: 0.31            # Total protein fraction (g protein / g DCW)
upper_threshold: 1.0e6   # Upper limit for kcat_app (s⁻¹)
lower_threshold: 1.0e-5  # Lower limit for kcat_app (s⁻¹)


# ================ FILES ================
medium_df: "data/processed/medium/faure_amn_medium.csv"
paxdb_path: "data/raw/paxdb/ecoli_whole_organism_integrated_511145.txt"
substrate_df: "data/processed/substrates/iml1515_substrates.csv"
sequence_df: "data/processed/uniprot/ecoli_uniprot_seqs.csv"
